/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6dae7cd9-cc45-40c4-88e1-6299fa09f8fa",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2f3l9nwqR",
    "aws_user_pools_web_client_id": "9of0sm6v2q0fi52ahfam1e08h",
    "oauth": {
        "domain": "nextamplifydbfd672c-dbfd672c-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;




